#!/bin/bash

g32 converttomillis.cpp
output=($1'times.csv')
cat $1 | grep '$ time\|real\|user\|sys' | grep -v 'Total time\|Average swap' | sed 's/$ time timeout 3600 java UnsafeMemory /x/g' | sed 's/real\t/ /g' | sed 's/user\t/ /g' | sed 's/sys\t/ /g' | tr -d '\n' | tr 'x' '\n' | tr ' ' ',' | ./a.out | sort &>$output
echo "" >>$output
