#!/bin/bash

rm -f lnxsrv06
touch lnxsrv06

date &>>lnxsrv06
cat /proc/cpuinfo | grep "model name" | uniq &>>lnxsrv06
java -version &>>lnxsrv06

for thread in 1 8 16 40
do
	for number in 100 10000 1000000 100000000
	do
		for size in 5 25 100
		do
			for type in "Null" "Synchronized" "Unsynchronized" "AcmeSafe"
			do
				echo "\$ time timeout 3600 java UnsafeMemory $type $thread $number $size" >>lnxsrv06
				(time timeout 3600 java UnsafeMemory $type $thread $number $size) &>>lnxsrv06
				echo "" >>lnxsrv06
			done
		done
	done
done
